---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1n8lspdc2k4pvcwnm90zu9wl9sfcj62sj56nzaeed7st6hc23f3ksufc5wf"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1n8lspdc2k4pvcwnm90zu9wl9sfcj62sj56nzaeed7st6hc23f3ksufc5wf"
stores:
  yaml:
    indent: 2
